# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: Assets\KRT\UnityGitBashHere

      - name: Build with UnityPacker
        run: |
          Get-Location
          ls
          Invoke-WebRequest -Uri https://github.com/FatihBAKIR/UnityPacker/releases/download/0.0.1/UnityPacker.exe -OutFile UnityPacker.exe
          Invoke-WebRequest -Uri https://github.com/FatihBAKIR/UnityPacker/releases/download/0.0.1/ICSharpCode.SharpZipLib.dll -OutFile ICSharpCode.SharpZipLib.dll
          .\UnityPacker Assets UnityGitBashHere
          Get-Location
          ls
      
      - uses: actions/upload-artifact@v2
        with:
          name: unitypackage
          path: "*.unitypackage"
